version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=md_user
      - MARIADB_DATABASE=magicdesk
      - MARIADB_PASSWORD=secret
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - db_data:/bitnami/mariadb

  #PhpMyAdmin
  phpmyadmin:
    depends_on: 
      - mariadb
    image: phpmyadmin/phpmyadmin
    ports:
      - '3001:80'
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
  magicdesk:
    tty: true
    image: bitnami/laravel:6-debian-9
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=md_user
      - DB_DATABASE=magicdesk
      - DB_PASSWORD=secret
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    privileged: true # Privileged mode could be required to run this container under Windows


volumes:
  db_data: